// step_5_write_exports.c
//
// Step 5 (verify): write build-time exports used by downstream commands.

#include "verify/steps/step_5_write_exports.h"

#include "common/build_log.h"

#include <stdio.h>
#include <string.h>

static int write_text_file(const char* path, const char* text) {
    FILE* f = fopen(path, "wb");
    if (!f) return 0;
    size_t n = fwrite(text, 1, strlen(text), f);
    fclose(f);
    return n == strlen(text);
}

int verify_step_5_write_exports(BuildContext* ctx) {
    if (!ctx) return 0;

    char swiftc_path_file[1024];
    char env_path[1024];

    snprintf(swiftc_path_file, sizeof(swiftc_path_file), "%s/.swiftc_path", ctx->build_dir);
    snprintf(env_path, sizeof(env_path), "%s/env.sh", ctx->build_dir);

    // .swiftc_path: single line + newline
    {
        char line[1200];
        snprintf(line, sizeof(line), "%s\n", ctx->swiftc);
        if (!write_text_file(swiftc_path_file, line)) {
            log_error("Failed writing: %s", swiftc_path_file);
            return 0;
        }
        log_info("Wrote: %s", swiftc_path_file);
    }

    // env.sh
    {
        char buf[4096];
        snprintf(buf, sizeof(buf),
                 "# Auto-generated by arduino-swift verify\n"
                 "# shellcheck disable=SC2034\n"
                 "\n"
                 "export SWIFTC=\"%s\"\n"
                 "export ARDUINO_BOARD=\"%s\"\n"
                 "export ARDUINO_FQBN=\"%s\"\n"
                 "export ARDUINO_CORE=\"%s\"\n"
                 "export SWIFT_TARGET=\"%s\"\n"
                 "export SWIFT_CPU=\"%s\"\n",
                 ctx->swiftc,
                 ctx->board,
                 ctx->fqbn,
                 ctx->core[0] ? ctx->core : "",
                 ctx->swift_target,
                 ctx->cpu);

        if (!write_text_file(env_path, buf)) {
            log_error("Failed writing: %s", env_path);
            return 0;
        }
        log_info("Wrote: %s", env_path);
    }

    return 1;
}
